name: Full Native Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        target: 
          - { name: "linux-x64", flags: "--disable-wallet" }
          - { name: "linux-x64-debug", flags: "--enable-debug" }
          # Tambahkan target lainnya di sini sesuai kebutuhan Anda
          - { name: "linux-aarch64", flags: "--disable-wallet" }
          # ... dst

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libtool autotools-dev automake pkg-config \
          libssl-dev libevent-dev libboost-all-dev libdb++-dev libsqlite3-dev

      - name: Build
        run: |
          ./autogen.sh
          ./configure --disable-zmq --disable-tests --disable-bench ${{ matrix.target.flags }} CXXFLAGS="-std=c++14"
          make -j$(nproc)

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: termucoind-${{ matrix.target.name }}
          path: src/termucoind
