name: Continuous Integration

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        target:
          - { name: "aarch64-linux", flags: "--disable-wallet" }
          - { name: "aarch64-linux-experimental", flags: "--enable-experimental --enable-c++14" }
          - { name: "armhf-linux", flags: "--disable-wallet" }
          - { name: "i686-linux", flags: "--enable-zmq" }
          - { name: "x86_64-linux-dbg", flags: "--enable-debug CPPFLAGS=-DDEBUG_LOCKORDER" }
          - { name: "x86_64-linux-nowallet", flags: "--disable-wallet" }
          - { name: "x86_64-linux-experimental", flags: "--enable-experimental --enable-c++14" }

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libtool autotools-dev automake pkg-config \
          libssl-dev libevent-dev libboost-all-dev libdb++-dev libsqlite3-dev \
          binutils-gold bsdmainutils python3 g++-multilib

      - name: Build
        run: |
          ./autogen.sh
          ./configure ${{ matrix.target.flags }} --disable-tests --disable-bench CXXFLAGS="-std=c++14"
          make -j$(nproc)

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: termucoin-${{ matrix.target.name }}
          path: src/termucoind
